### ISSUE TITLE
179.最大数.js 这个题目的解法有些问题

### ISSUE THREAD

**Issue by kungua** [qianlongdoit/leetCode#1]
179.最大数.js 这个题目的目前的解法过不了 `[0,9,8,7,6,5,4,3,2,1]` 这组测试用例

**Comment by qianlongdoit** [comment]
> [0,9,8,7,6,5,4,3,2,1]

看了之前的提交记录，发现这个没有更正就提交了。加一个长度判断就好了，已经更正了。
